### ISSUE TITLE
First time --adhoc, need --yaml

### ISSUE THREAD

**Issue by noorula** [valohai/valohai-cli#198]
When running an --adhoc execution for the first time in a project, you will need to use the --yaml flag even though valohai.yaml is in the root directory. Running the execution again works fine.

**Comment by orasimus** [comment]
But before you've done it, repeated `--adhoc` fails.

Stack trace:
```
Traceback (most recent call last):
  File "/Users/otso/envs/vh/bin/vh", line 8, in <module>
    sys.exit(cli())
  File "/Users/otso/envs/vh/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/otso/envs/vh/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/otso/envs/vh/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/otso/envs/vh/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/otso/envs/vh/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/otso/envs/vh/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/otso/envs/vh/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/otso/envs/vh/lib/python3.9/site-packages/valohai_cli/commands/execution/run/frontend_command.py", line 87, in run
    config = project.get_config(commit_identifier=commit, yaml_path=yaml)
  File "/Users/otso/envs/vh/lib/python3.9/site-packages/valohai_cli/models/project.py", line 43, in get_config
    filename = self.get_config_filename(yaml_path=yaml_path)
  File "/Users/otso/envs/vh/lib/python3.9/site-packages/valohai_cli/models/project.py", line 66, in get_config_filename
    return os.path.join(self.directory, used_yaml_path)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```
